# Generated by Django 2.2.1 on 2019-05-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implement', '0004_auto_20190522_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='short_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
