# Generated by Django 2.2.1 on 2019-05-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implement', '0005_auto_20190522_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
