# Generated by Django 2.2.1 on 2019-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implement', '0006_auto_20190522_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='clicks',
            field=models.BooleanField(default=0),
        ),
    ]
