# Generated by Django 2.2.1 on 2019-05-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implement', '0007_urlmodel_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
